name: MentionSound
version: 0.1.0
main: DavyCraft648\MentionSound\MentionSound
api: 5.0.0
# Update pm4 -> pm5 by xBibou : discord.gg/pocketmine | discord.gg/nephelia
website: https://github.com/DavyCraft648/MentionSound
description: A sound notifier when someone mentions you
author: DavyCraft648
commands:
  mentionsound:
    description: Open MentionSound Menu
    aliases:
      - mentsound
    permission: mentionsound.command
    permission-message: "§cYou do not have permission to use this command!"
permissions:
  mentionsound.command:
    default: true
